name: Deploy Docs

on: 
  push:
    tags:
      - v*
      - latest

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - clone docs
      uses: actions/checkout@v2
      with:
        path: docs-files

    - clone frontend
      uses: actions/checkout@v2
      with:
        repository: 'hstreamdb/hstreamdb-docs-frontend'
        path: frontend

    - name: use node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.15

    - name: set env
      run: |
         VERSION=$(echo ${{ github.ref }} | sed -r  "s ^refs/heads/|^refs/tags/(.*) \1 g")
         echo "DOCSBRANCH=$VERSION" >> $GITHUB_ENV
         echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: move files
      run: |
        mkdir -p frontend/docs/en/${VERSION}/
        mkdir -p frontend/docs/zh/${VERSION}/
        cp -r docs-files/en/* frontend/docs/en/${VERSION}/
        cp -r docs-files/zh/* frontend/docs/zh/${VERSION}/
        rm frontend/docs/*.md

    - name: build docs
      run: |
        cd frontend
        yarn && yarn build

    - name: use python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: upload dist
      run: |
        pip3 install coscmd
        coscmd config -a ${{ secrets.COS_ID }} -s ${{ secrets.COS_KEY }} -b ${{ secrets.COS_NAME }} -r ${{ secrets.COS_REGION }}
        coscmd delete -r -f docs || true
        coscmd delete -r -f docs-assets || true
        coscmd delete -r -f docs-images || true
        coscmd upload -r frontend/.vuepress/dist/ /

    - name: flush CDN
      run: |
        pip3 install tccli
        tccli configure set secretId ${{ secrets.COS_ID }}
        tccli configure set secretKey ${{ secrets.COS_KEY }}
        tccli configure set region ${{ secrets.COS_REGION }}
        tccli cdn PurgePathCache --Paths '["https://test.hstream.io/"]' --FlushType flush
