name: Deploy Docs

on: 
  push:
    tags:
      - v*
      - latest

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: use node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.15
    - name: set env
      run: |
         VERSION=${{ github.ref }} | sed -r  "s ^refs/heads/|^refs/tags/(.*) \1 g"
         echo "DOCSBRANCH=$VERSION" >> $GITHUB_ENV
         echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: build docs
      run: |
        mkdir -p tmp/en/${VERSION}/ && mkdir -p tmp/zh/${VERSION}/
        mv docs/en/* tmp/en/${VERSION}/ && mv docs/zh/* tmp/zh/${VERSION}/
        rm -rf docs/* && cp -r tmp/* docs/
        rm -rf tmp && rm ./*.md
        yarn && yarn build

    - name: use python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: upload dist
      run: |
        pip3 install coscmd
        coscmd config -a ${{ secrets.COS_ID }} -s ${{ secrets.COS_KEY }} -b ${{ secrets.COS_NAME }} -r ${{ secrets.COS_REGION }}
        coscmd upload -r ./.vuepress/dist/ /

    - name: flush CDN
      run: |
        pip3 install tccli
        tccli configure set secretId ${{ secrets.COS_ID }}
        tccli configure set secretKey ${{ secrets.COS_KEY }}
        tccli configure set region ${{ secrets.COS_REGION }}
        tccli cdn PurgePathCache --Paths '["https://test.hstream.io/"]' --FlushType flush
